server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway
  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service
          uri: lb://gongcaedan-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - PreserveHostHeader

        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/user/**,/login/**,/oauth2/**,/auth/**
          filters:
            - PreserveHostHeader

        - id: pledge-tracker
          uri: lb://pledge-tracker
          predicates:
            - Path=/api/pledges/**,/api/milestones/**,/api/milestone-logs/**
          filters:
            - PreserveHostHeader
            - AddRequestHeader=Authorization, "#{request.headers.Authorization}"

        - id: gongcaedan_candidate
          uri: lb://gongcaedan_candidate
          predicates:
            - Path=/api/candidates/**,/api/parties/**
          filters:
            - PreserveHostHeader
            - AddRequestHeader=Authorization, "#{request.headers.Authorization}"

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka