server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            # OAuth2 시작/콜백을 userservice로 프록시
            - id: oauth2-proxy
              uri: lb://userservice
              predicates:
                - Path=/oauth2/**,/login/**,/auth/**
              filters:
                - PreserveHostHeader

            # 기존 라우트들
            - id: auth-through-userservice
              uri: lb://userservice
              predicates:
                - Path=/auth/**
              filters:
                - PreserveHostHeader

            - id: userservice
              uri: lb://userservice
              predicates:
                - Path=/user/**

            - id: pledge-tracker
              uri: lb://pledge-tracker
              predicates:
                - Path=/api/pledges/**,/api/milestones/**,/api/milestone-logs/**
              filters:
                - PreserveHostHeader

            - id: gongcaedan_candidate
              uri: lb://gongcaedan_candidate
              predicates:
                - Path=/api/candidates/**,/api/parties/**
              filters:
                - PreserveHostHeader

security:
  jwt:
    secret-base64: ${JWT_SECRET_BASE64}

eureka:
  client:
    service-url:
      defaultZone: http://eurekaserver:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
